app:
  frontend:
    url: https://thexuong.xuansown.id.vn
  cors:
    # Comma-separated list of allowed origins for CORS
    # Production: replace with real domains, e.g. https://thexuong.com,https://www.thexuong.com
    allowed-origins: https://thexuong.xuansown.id.vn,http://localhost:5173,http://localhost:8080,http://127.0.0.1:5173,http://127.0.0.1:8080

  cloudflare:
    r2:
      endpoint: https://e1171a0fa6f3c8a1dd3c702025523585.r2.cloudflarestorage.com
      access-key: "893ec4cd3728fc8ae343fa89cb162db9"
      secret-key: "0706ee997a763aabafd14029cd9c1268a24a7ef0e137f3a73cf3d64b19030851"
      bucket-name: the-xuong-media
      public-url: https://pub-3fbae0ca10794f42ad228e5d2cf7ce04.r2.dev # Đường dẫn subdomain public ảnh

  google:
    maps:
      api-key: ${GOOGLE_MAPS_API_KEY:}
      language: vi
      region: vn

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 425173599446-qd901q0i2s75atio7pmqq2t8ckou3tdv.apps.googleusercontent.com
            client-secret: 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
        provider:
          google:
            user-name-attribute: email
