spring.application.name=TheXuong
server.port=8080
server.forward-headers-strategy=framework

# ============================================================
# SQL Server Database
# ============================================================
spring.datasource.url=jdbc:sqlserver://localhost:1444;databaseName=dbTheXuong;encrypt=false;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=Sontran1903@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
# map sang cột nvarchar
spring.jpa.properties.hibernate.use_nationalized_character_data=true
logging.level.org.hibernate=warn
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ============================================================
# Cấu hình gửi mail
# ============================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tranxuanson9423@gmail.com
spring.mail.password=snfm antm pohv jbob
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ============================================================
# JWT (Stateless authentication)
# ============================================================
app.jwt.secret=GG1sV6EI53zr15rzi/HaFvUDA4z4jlKuBDwSPwcZYtQ=
app.jwt.expiration=86400000

# ============================================================
# VNPay
# ============================================================
vnpay.tmn-code=VSU1QOMH
vnpay.secret-key=W3KWLMYBGF7SN8JRFTAQNUXN6F2U5OUS
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=https://thexuong.xuansown.id.vn/vnpay-return
