spring:
  datasource:
    url: jdbc:sqlserver://localhost:1444;databaseName=dbTheXuong;encrypt=true;trustServerCertificate=true
    username: sa
    password: Sontran1903@
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 425173599446-qd901q0i2s75atio7pmqq2t8ckou3tdv.apps.googleusercontent.com # GOOGLE_CLIENT_ID
            client-secret: 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 # GOOGLE_CLIENT_SECRET
        provider:
          google:
            user-name-attribute: email

jwt:  
  secret: KhoaBiMatPhaiRatDaiDeBaoMatJWTTheXuongProject2024
  expiration: 3600000 # 1 giờ