package com.example.thexuong.controller;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.testcontainers.containers.MSSQLServerContainer;

import org.springframework.boot.test.mock.mockito.MockBean;
import com.example.thexuong.service.CloudflareR2Service;
import com.example.thexuong.service.EmailService;

import org.springframework.transaction.annotation.Transactional;

/**
 * Base class for all Integration Tests.
 * It spins up a real MSSQL Docker container using Testcontainers.
 * The DB schema will be generated by Hibernate automatically (ddl-auto=update).
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureMockMvc
@ActiveProfiles("test") // We will create application-test.properties later
@Transactional
public abstract class BaseIntegrationTest {

    @Autowired
    protected MockMvc mockMvc;

    @MockBean
    protected CloudflareR2Service r2Service;

    @MockBean
    protected EmailService emailService;

    private static final MSSQLServerContainer<?> MSSQL_CONTAINER = new MSSQLServerContainer<>("mcr.microsoft.com/mssql/server:2022-latest")
            .acceptLicense();

    static {
        MSSQL_CONTAINER.start();
    }

    @DynamicPropertySource
    static void mssqlProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", MSSQL_CONTAINER::getJdbcUrl);
        registry.add("spring.datasource.username", MSSQL_CONTAINER::getUsername);
        registry.add("spring.datasource.password", MSSQL_CONTAINER::getPassword);
        // Important: For Integration test, we need Hibernate to create tables automatically on the blank test DB
        registry.add("spring.jpa.hibernate.ddl-auto", () -> "update");
    }
}
